name: Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  push_to_gcr:
    name: Push Docker Image to GCR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Docker login
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      run: echo $DOCKER_LOGIN | docker login -u _json_key_base64 --password-stdin https://europe-west9-docker.pkg.dev
    
    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker europe-west9-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        # Build the Docker image
        docker build -t europe-west9-docker.pkg.dev/my-lab-production-415213/my-lab-artifact-registry/front_dns_explorer:1.0.1 .
        
        # Push the Docker image to GCR
        docker push europe-west9-docker.pkg.dev/my-lab-production-415213/my-lab-artifact-registry/front_dns_explorer:1.0.1

    - name: Logout from Docker registry
      run: docker logout
